### ISSUE TITLE
Generate data for SAPT

### ISSUE THREAD

**Issue by ALescoulie** [calpolyccg/MDSAPT_demo#2]
Putting a to myself here to add data in the repo, since we can't actually run SAPT in the notebook. Also need to figure out how to load it in and present it.

**Comment by armcdona** [comment]
So you could run SAPT in the notebook it would just take a long time. But you can issue psi4 calls in the notebook.

**Comment by ALescoulie** [comment]
I could issue the psi4 commands, but I think that the amount of time it would take may reduce how interesting our demo is.
